apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: webapp-pod
  labels:
    app: employees
spec:
  type: NodePort
  selector:
    app: employees
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000  # Specify the node port you want to use (must be in the range 30000-32767)
    protocol: TCP
    name: http
